@startuml
node "purchase-bootstrap"

package "Presentation" {
  node "purchase-rest"
}

package "Domain" {
  node "purchase-domain"
}


package "Application Service" {
  node "purchase-application"
}

package "Infrastructure" {
  node "purchase-data-jpa"

  node "purchase-data-rest"
}

database "H2" {

}


[purchase-bootstrap] --> [purchase-rest]
[purchase-bootstrap] --> [purchase-data-jpa]
[purchase-bootstrap] --> [purchase-data-rest]

[purchase-data-rest] --> [purchase-domain]
[purchase-data-jpa] --> [purchase-domain]
[purchase-application] --> [purchase-domain]

[purchase-rest] --> [purchase-application]
[purchase-data-jpa] -[dashed]->H2 : use


@enduml